### ISSUE TITLE
Erro ao clicar sobre uma emenda

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn-brasil/Parlametria#20]
No projeto **Leg.go**, ao navegar pelas proposições legislativas, na seção "*Análise das emendas*", clicar o link de uma emenda leva a uma página inexistente.

**Comment by jeffersonrpn** [comment]
Obrigado pela colaboração.
Repassamos a issue para a equipe do leg.go, que está em outro repositório. [Issues do leg.go](https://github.com/analytics-ufcg/leggo-frontend/issues)

**Comment by augusto-herrmann** [comment]
Obrigado pela informação. Já havia [uma issue sobre isso](https://github.com/analytics-ufcg/leggo-frontend/issues/376) por lá. Sugiro colocar um link para o outro repositório no README.
